Fixes for mix releases
primait/prima_opentelemetry_ex pull request #23
Opened 2022-09-02 12:08 UTC by mosic

I'm in processes of migrating Stonehenge from Distillery to Mix Releases, and I ran into two issues:

* Having `opentelemetry` in `included_applications` breaks the release with this message:
    ```
    ** (Mix) :opentelemetry is listed both as a regular application and as an included application
    ```

* `opentelemetry` has a breaking change in 1.1.0, and fails to compile when other `opentelemetry_*` apps are used - it looks like all of the libraries which use `instrumentation_scope` will have to be updated first.
https://github.com/open-telemetry/opentelemetry-erlang/blob/main/CHANGELOG.md#api-110---2020-8-31

2022-09-05 09:59 UTC, Fs00 requested changes
Thanks for reporting the problems! I think that we should fix them using another approach though.

2022-09-05 09:59 UTC, Fs00 commented on mix.exs
> +      {:opentelemetry_exporter, "~> 1.0.0"}
The compilation issue has been fixed in the [release 1.1.1 of the OTel SDK](https://github.com/open-telemetry/opentelemetry-erlang/blob/main/CHANGELOG.md#sdk-111---2022-09-02), could please update the dependencies instead of restricting the usable versions?
```suggestion
      {:opentelemetry, "~> 1.1"},
      {:opentelemetry_api, "~> 1.1"},
      {:opentelemetry_exporter, "~> 1.1"}
```

2022-09-05 09:59 UTC, Fs00 commented on mix.exs
> +      {:opentelemetry_ecto, "~> 1.0.0"},
These shouldn't be necessary anymore once you update the OTel SDK

2022-09-05 09:59 UTC, Fs00 commented on mix.exs
> +      applications: [
This is not a viable approach since the `opentelemetry` application must be started by the `PrimaOpentelemetryEx.setup()` method and not automatically.
I think that a more correct way to fix the Mix release problem is to add `runtime: false` to the deps that are also in included_applications, so that they don't get automatically included in the `applications` list.

2022-09-05 11:30 UTC, mosic commented on mix.exs
> +      applications: [
I just tried it, even after setting `runtime: false` on all of the deps in `prima_opentelemetry_ex` I'm getting the same error:
```
** (Mix) :opentelemetry is listed both as a regular application and as an included application
```

What's the reason we have `included_applications` anyway? Since the deps are included and we start them manually with `PrimaOpentelemetryEx.setup()`, it should be safe to remove that line altogether? It worked in my test at least.

2022-09-05 15:23 UTC, mosic commented on mix.exs
> +      applications: [
Makes sense, let me know what he things :+1

2022-09-06 14:47 UTC, mosic commented on mix.exs
> +      applications: [
Looks great, should we get it merged?

2022-09-06 15:13 UTC, Fs00 commented on mix.exs
> +      applications: [
Sure! Sadly I don't have the permission to do it myself 😬

2022-09-06 15:13 UTC, Fs00 approved these changes

2022-09-07 08:07 UTC, merged

2022-09-07 09:43 UTC, Fs00 commented
@mosic We've just released version 1.1.1 with the fix! Let us know if there are any problems

2022-09-07 09:49 UTC, mosic commented
Thanks @Fs00, we just switched back to it!